version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

  node:
    image: node:alpine
    ports:
      - 5555:5555
      - 3000:3000
    volumes:
        - ./:/app
    entrypoint: node -i
    stdin_open : true
    tty: true
    working_dir: /app